# Random Forest Algorithm
## Patient with abnormal Blood pressure Model

In [2]:
# importing required libraries

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os

In [3]:
os.chdir("C:/Users/vishw/OneDrive/Documents/Imarticus/Python/Machine Learning")

In [4]:
# importing and reading the file
abp = pd.read_csv("Patient_with_abnormal_bloodpressure.csv")

In [5]:
# print first 5 records
abp.head()

,Patient_Number,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
0,1,1,11.28,0.90,34,23,1,1.0,0,45961,48071,NaN,2,1,1
1,2,0,9.75,0.23,54,33,1,NaN,0,26106,25333,205.0,3,0,0
2,3,1,10.79,0.91,70,49,0,NaN,0,9995,29465,67.0,2,1,0
3,4,0,11.00,0.43,71,50,0,NaN,0,10635,7439,242.0,1,1,0
4,5,1,14.17,0.83,52,19,0,NaN,0,15619,49644,397.0,2,0,0

In [6]:
abp.tail()

,Patient_Number,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
1995,1996,1,10.14,0.02,69,26,1,NaN,1,26118,47568,144.0,3,1,0
1996,1997,1,11.77,1.00,24,45,1,1.0,1,2572,8063,NaN,3,1,1
1997,1998,1,16.91,0.22,18,42,0,NaN,0,14933,24753,NaN,2,1,1
1998,1999,0,11.15,0.72,46,45,1,NaN,1,18157,15275,253.0,3,0,1
1999,2000,1,11.36,0.09,41,45,0,NaN,0,20729,30463,230.0,1,1,0

In [7]:
# print shape of the data
abp.shape   # 2000 rows, 15 columns

(2000, 15)

In [9]:
# check NULL values if any
abp.isnull().sum()

Patient_Number                      0
Blood_Pressure_Abnormality          0
Level_of_Hemoglobin                 0
Genetic_Pedigree_Coefficient       92
Age                                 0
BMI                                 0
Sex                                 0
Pregnancy                        1558
Smoking                             0
Physical_activity                   0
salt_content_in_the_diet            0
alcohol_consumption_per_day       242
Level_of_Stress                     0
Chronic_kidney_disease              0
Adrenal_and_thyroid_disorders       0
dtype: int64

In [10]:
# replacing null values with binary '0' to make it absent in the respective variable

abp.Pregnancy = abp.Pregnancy.fillna(0) # 1 is for female and 0 is for male, hence feeling in all NULL's with 0
abp.Genetic_Pedigree_Coefficient = abp.Genetic_Pedigree_Coefficient.fillna(abp.Genetic_Pedigree_Coefficient.median()) # mean and median value is close so feeling the null's with median
abp.alcohol_consumption_per_day = abp.alcohol_consumption_per_day.fillna(abp.alcohol_consumption_per_day.median())  # mean and median value is close so feeling the null's with median

In [12]:
# checking the records for NULLS
abp.isnull().sum()  # No NULL values present.

Patient_Number                   0
Blood_Pressure_Abnormality       0
Level_of_Hemoglobin              0
Genetic_Pedigree_Coefficient     0
Age                              0
BMI                              0
Sex                              0
Pregnancy                        0
Smoking                          0
Physical_activity                0
salt_content_in_the_diet         0
alcohol_consumption_per_day      0
Level_of_Stress                  0
Chronic_kidney_disease           0
Adrenal_and_thyroid_disorders    0
dtype: int64

In [14]:
# print desciption of the data set
abp = abp.iloc[: , 1:15]
abp.describe(include = 'all')  # this will print all the columns which has numeric and non numeric data

,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.0000,2000.000000
mean,0.493500,11.710035,0.494595,46.558500,30.081500,0.496000,0.099500,0.509500,25254.424500,24926.097000,250.886500,2.012500,0.5050,0.443500
std,0.500083,2.186701,0.284945,17.107832,11.761208,0.500109,0.299407,0.500035,14015.439623,14211.692586,134.676589,0.823822,0.5001,0.496922
min,0.000000,8.100000,0.000000,18.000000,10.000000,0.000000,0.000000,0.000000,628.000000,22.000000,0.000000,1.000000,0.0000,0.000000
25%,0.000000,10.147500,0.250000,32.000000,20.000000,0.000000,0.000000,0.000000,13605.750000,13151.750000,144.000000,1.000000,0.0000,0.000000
50%,0.000000,11.330000,0.490000,46.000000,30.000000,0.000000,0.000000,1.000000,25353.000000,25046.500000,250.000000,2.000000,1.0000,0.000000
75%,1.000000,12.945000,0.730000,62.000000,40.000000,1.000000,0.000000,1.000000,37382.250000,36839.750000,360.250000,3.000000,1.0000,1.000000
max,1.000000,17.560000,1.000000,75.000000,50.000000,1.000000,1.000000,1.000000,49980.000000,49976.000000,499.000000,3.000000,1.0000,1.000000

In [15]:
# converting columns in category type to perform random forest
abp.Blood_Pressure_Abnormality = abp.Blood_Pressure_Abnormality.astype("category")
abp.Sex = abp.Sex.astype("category")
abp.Pregnancy = abp.Pregnancy.astype("category")
abp.Smoking = abp.Smoking.astype("category")
abp.Level_of_Stress = abp.Level_of_Stress.astype("category")
abp.Chronic_kidney_disease = abp.Chronic_kidney_disease.astype("category")
abp.Adrenal_and_thyroid_disorders = abp.Adrenal_and_thyroid_disorders.astype("category")

In [17]:
# importing RNF from scikit learn
from sklearn.ensemble import RandomForestClassifier

# importing confusion matrix from scikit learn to check the data where it lies
from sklearn.metrics import confusion_matrix

# splitting data in train and test to perform the procedure

from sklearn.model_selection import train_test_split

In [18]:
# splitting data into 'X' and 'Y'

abp_x = abp.iloc[: , 1:14]
abp_y = abp.iloc[: , 0]   # blood pressure abnormality is taget (Y) variable

In [19]:
# splitting data into train and test 
abp_x_train, abp_x_test, abp_y_train, abp_y_test = train_test_split(abp_x, abp_y, test_size = .2, random_state = 420)

In [20]:
rfc = RandomForestClassifier(n_estimators=100) # creating a RNF classifier with 100 trees

In [21]:
# fitting the model
rfc.fit(abp_x_train, abp_y_train)

RandomForestClassifier()

In [22]:
# prediction on 'x' test
pred_value = rfc.predict(abp_x_test)
pred_value

array([1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1], dtype=int64)

In [23]:
# printing matrix on 'y' test and pred_value

mat_abp = confusion_matrix(abp_y_test, pred_value)
mat_abp

array([[167,  33],
       [ 23, 177]], dtype=int64)

In [25]:
# printing the accuracy score

from sklearn.metrics import accuracy_score
accuracy_score(abp_y_test, pred_value)

0.86

In [27]:

from sklearn.metrics import recall_score   # Tp /tp +fn
recall_score(abp_y_test, pred_value)

0.885

In [28]:

from sklearn.metrics import precision_score # tp / tp+fp
precision_score(abp_y_test, pred_value)

0.8428571428571429

In [46]:
# rfc.predict_proba(abp_x_test)  # prediction in probability

In [31]:
# printing the important features score of the model variables
rfc.feature_importances_

array([0.22361602, 0.27164844, 0.05610868, 0.04589693, 0.01454986,
       0.00660863, 0.00971923, 0.0589484 , 0.06152043, 0.05188575,
       0.01533226, 0.12183488, 0.0623305 ])

In [33]:
# converting into a list
list1 = list(rfc.feature_importances_)
list1

[0.22361602251879079,
 0.27164843829171725,
 0.05610867645212814,
 0.04589692615871998,
 0.014549855836751394,
 0.006608633459000521,
 0.009719225694524901,
 0.058948397606318766,
 0.06152043308719429,
 0.051885749377895925,
 0.01533226012858719,
 0.12183487694502132,
 0.06233050444334966]

In [34]:
# printing one to one mapping with the feature name and their Importance Score
feature_importance_rf = pd.DataFrame({"Feature_Name " : abp_x_train.columns, "Importance" : list1})

In [35]:
feature_importance_rf

                    Feature_Name   Importance
0             Level_of_Hemoglobin    0.223616
1    Genetic_Pedigree_Coefficient    0.271648
2                             Age    0.056109
3                             BMI    0.045897
4                             Sex    0.014550
5                       Pregnancy    0.006609
6                         Smoking    0.009719
7               Physical_activity    0.058948
8        salt_content_in_the_diet    0.061520
9     alcohol_consumption_per_day    0.051886
10                Level_of_Stress    0.015332
11         Chronic_kidney_disease    0.121835
12  Adrenal_and_thyroid_disorders    0.062331

In [36]:
# printing features in ascending order with respect to the feature's highest importance
feature_importance_rf = feature_importance_rf.sort_values("Importance", ascending = False)
feature_importance_rf

                    Feature_Name   Importance
1    Genetic_Pedigree_Coefficient    0.271648
0             Level_of_Hemoglobin    0.223616
11         Chronic_kidney_disease    0.121835
12  Adrenal_and_thyroid_disorders    0.062331
8        salt_content_in_the_diet    0.061520
7               Physical_activity    0.058948
2                             Age    0.056109
9     alcohol_consumption_per_day    0.051886
3                             BMI    0.045897
10                Level_of_Stress    0.015332
4                             Sex    0.014550
6                         Smoking    0.009719
5                       Pregnancy    0.006609

## Learning : 
### From the above findings we can interpret that the "Genetic_Pedigree_Coefficient" is the most significant features to trigger abnormal blood pressure in patients followed by "Level_of_Hemoglobin" and "Chronic_kidney_disease". Where "Smoking" and "Pregnancy" are the least considerable features based on   the model.

### To use the model with given data to measure individual's blood pressure with the "user define function" performing following task.

In [44]:
from termcolor import colored  # to print in different color

def enter_input():
    Adernal_and_thyroid_disorders = eval(input("value of Adernal_and_thyroid_disorders(1: disorder, 0: Nodisorder)"))
    Age                           = eval(input("value of age::"))
    BMI                           = eval(input("value of : BMI"))
    Chronic_kidney_disease        = eval(input("value of Chronic_kidney_disease(1: for Disease, 0 : No disease)"))
    Genetic_Pedigree_Coefficient  = eval(input("value of Genetic_pedigree_Coefficient(1 : for Genetic, 0 : for not)"))
    Level_of_Hemoglobin           = eval(input("value of level_of_Hemoglobin"))
    Level_of_Stress               = eval(input("value of Level_of_Stress(1 or 2 or 3. 3 Is highest level of Stress)"))
    Physical_activity             = eval(input("value of physical_activity"))
    Pregnancy                     = eval(input("value of Pregnancy(1:if pregnant)"))
    Sex                           = eval(input("value of Sex(1 for female, 0 for male)"))
    Smoking                       = eval(input("value of Smoking(1 if smoking)"))
    alcohol_consumption_per_day   = eval(input("value of alcohol_consumption_per_day"))
    salt_content_in_the_diet      = eval(input("value of salt_content_in_the_diet"))
    df_bp                         = pd.DataFrame({"Adernal_and_thyroid_disorders" :[Adernal_and_thyroid_disorders],
                                                 "Age" : [Age],
                                                  "BMI" : [BMI],
                                                 "Chronic_kidney_disease" : [Chronic_kidney_disease],
                                                 "Genetic_Pedigree_Coefficient" : [Genetic_Pedigree_Coefficient],
                                                 "Level_of_Hemoglobin": [Level_of_Hemoglobin],
                                                 "Level_of_Stress" :[Level_of_Stress],
                                                 "Physical_activity" : [Physical_activity],
                                                 "Pregnancy" : [Pregnancy], "Sex" : [Sex],
                                                 "Smoking" : [Smoking],
                                                 "alcohol_consumption_per_day" : [alcohol_consumption_per_day],
                                                 "salt_content_in_the_diet" : [salt_content_in_the_diet],})
    pred_bp                       = rfc.predict(df_bp)
    pred_prob                     = rfc.predict_proba(df_bp)
    print(colored("-----------------------------------------------------------------", "yellow"))
    print(colored("-----------------------------------------------------------------", "blue"))
    print(colored("-----------------------------------------------------------------", "green"))
    if pred_bp ==0:
        print(colored("congrates--You do NOT have BP Abnormality--", "green"))
    else:
        print(colored("Warning --- You have Blood Pressure Abnormality --", "red"))
        print(colored("-------------------------------------------------------------", "yellow"))
        print(colored("--------------------------------------------------------------", "blue"))
        print(colored("--------------------------------------------------------------", "green"))
        print( "Your Probability of being Normal  ::: ", pred_prob[0][0] )
        print(colored("-------------------------------------------------------------", "yellow"))
        print(colored("--------------------------------------------------------------", "blue"))
        print(colored("--------------------------------------------------------------", "green"))

In [45]:
enter_input()

value of Adernal_and_thyroid_disorders(1: disorder, 0: Nodisorder)0
value of age::36
value of : BMI19
value of Chronic_kidney_disease(1: for Disease, 0 : No disease)0
value of Genetic_pedigree_Coefficient(1 : for Genetic, 0 : for not)0
value of level_of_Hemoglobin19
value of Level_of_Stress(1 or 2 or 3. 3 Is highest level of Stress)1
value of physical_activity62000
value of Pregnancy(1:if pregnant)0
value of Sex(1 for female, 0 for male)0
value of Smoking(1 if smoking)0
value of alcohol_consumption_per_day0
value of salt_content_in_the_diet2000
-----------------------------------------------------------------
-----------------------------------------------------------------
-----------------------------------------------------------------
Warning --- You have Blood Pressure Abnormality --
-------------------------------------------------------------
--------------------------------------------------------------
--------------------------------------------------------------
Your Probability of being Normal  :::  0.38
-------------------------------------------------------------
--------------------------------------------------------------
--------------------------------------------------------------